version: '3'

services:
  backend:
    image: node:12
    working_dir: "/app/backend"
    volumes:
      - "../../:/app"
    command: "npm run dev"

  frontend:
    image: node:12
    working_dir: "/app/frontend"
    ports:
      - "4200:4200"
    volumes:
      - "../../:/app"
    command: "npm run docker:dev"
